{% set name = "opentelemetry-instrumentation-urllib3" %}
{% set version = "0.59b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 2de8d53a746bba043be1bc8f3246e1b131ebb6e94fe73601edd8b2bd91fe35b8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.12,<2
    - opentelemetry-instrumentation =={{ version }}
    - opentelemetry-semantic-conventions =={{ version }}
    - opentelemetry-util-http =={{ version }}
    - wrapt >=1.0.0,<2.0.0
  run_constrained:
    - urllib3 >=1.0.0,<3.0.0

# Tests disabled:
# E   ModuleNotFoundError: No module named 'opentelemetry.test'
# https://pypi.org/project/opentelemetry-test-utils, not in the main channel.
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation.urllib3
  commands:
    - pip check
  requires:
    - pip
    - urllib3 >=1.0.0,<3.0.0

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib3
  summary: OpenTelemetry urllib3 instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: This library allows tracing HTTP requests made by the urllib3 library.
  dev_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib3
  doc_url: https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-urllib3/README.rst

extra:
  recipe-maintainers:
    - mariusvniekerk
