{% set name = "opentelemetry-instrumentation-urllib3" %}
{% set version = "0.28b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-urllib3-{{ version }}.tar.gz
  sha256: 9e844b74e82696ca2e7687af073b2054887eddeaf4c91d578fae36685335d163

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.28b0
    - opentelemetry-semantic-conventions ==0.28b0
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - urllib3 <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    - httpretty ~=1.0
    - urllib3 <2.0.0,>=1.0.0
    - opentelemetry-util-http ==0.28b0
    # - opentelemetry-test-utils ==0.26b1
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.27b0
    # - opentelemetry-test-utils ==0.28b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib3
  summary: OpenTelemetry urllib3 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
